version: '3.3'

services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
    - "27017:27017"
    volumes: 
    - mongodbdata:/data/db
    # command: [--auth]
    restart: always

volumes:
  mongodbdata:
